### ISSUE TITLE
Error when running endpoint

### ISSUE THREAD

**Issue by kleenkanteen** [tuffstuff9/nextjs-pdf-parser#1]
edit: nvm I had not cloned the repo but copy pasted the route.ts into my existing small project. Let me try cloning from scratch and trying. You can ignore this first post and skip to the next.

second edit: The below error's solution is in the readme. Just figured it out.

I am on Next.js 13.4.12. When I run your code and call the route I get this error:

```
$ yarn dev
yarn run v1.22.21
$ next dev
- ready started server on 0.0.0.0:3000, url: http://localhost:3000
- info Loaded env from T:\coding\speed-grader\speed-grader\.env
- event compiled client and server successfully in 700 ms (20 modules)
- wait compiling...
- event compiled client and server successfully in 224 ms (20 modules)
- wait compiling /src/middleware (client and server)...
- event compiled successfully in 899 ms (273 modules)
<w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (104kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
- wait compiling /page (client and server)...

🌼   daisyUI 4.4.18
├─ ✔︎ 2 themes added            https://daisyui.com/docs/themes
╰─ ❤︎ Support daisyUI project:  https://opencollective.com/daisyui

- event compiled client and server successfully in 5.8s (767 modules)
- wait compiling /api/text/route (client and server)...
- event compiled client and server successfully in 1419 ms (814 modules)
- wait compiling /_error (client and server)...
- error node_modules\pdf2json\lib\pdf.js (72:0) @ eval
- error Error [ReferenceError]: nodeUtil is not defined
    at eval (eval at <anonymous> (webpack-internal:///(rsc)/./node_modules/pdf2json/lib/pdf.js), <anonymous>:1226:1)
    at eval (webpack-internal:///(rsc)/./node_modules/pdf2json/lib/pdf.js:79:1)
    at (rsc)/./node_modules/pdf2json/lib/pdf.js (T:\coding\speed-grader\speed-grader\.next\server\app\api\text\route.js:854:1)
    at __webpack_require__ (T:\coding\speed-grader\speed-grader\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./node_modules/pdf2json/pdfparser.js:9:69)
    at (rsc)/./node_modules/pdf2json/pdfparser.js (T:\coding\speed-grader\speed-grader\.next\server\app\api\text\route.js:975:1)
    at __webpack_require__ (T:\coding\speed-grader\speed-grader\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./src/app/api/text/route.ts:10:66)
    at (rsc)/./src/app/api/text/route.ts (T:\coding\speed-grader\speed-grader\.next\server\app\api\text\route.js:788:1)
    at __webpack_require__ (T:\coding\speed-grader\speed-grader\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2Fapi%2Ftext%2Froute&page=%2Fapi%2Ftext%2Froute&appPaths=&pagePath=private-next-app-dir%2Fapi%2Ftext%2Froute.ts&appDir=T%3A%5Ccoding%5Cspeed-grader%5Cspeed-grader%5Csrc%5Capp&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&rootDir=T%3A%5Ccoding%5Cspeed-grader%5Cspeed-grader&isDev=true&tsconfigPath=tsconfig.json&basePath=&assetPrefix=&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D!:15:118)
    at (rsc)/./node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2Fapi%2Ftext%2Froute&page=%2Fapi%2Ftext%2Froute&appPaths=&pagePath=private-next-app-dir%2Fapi%2Ftext%2Froute.ts&appDir=T%3A%5Ccoding%5Cspeed-grader%5Cspeed-grader%5Csrc%5Capp&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&rootDir=T%3A%5Ccoding%5Cspeed-grader%5Cspeed-grader&isDev=true&tsconfigPath=tsconfig.json&basePath=&assetPrefix=&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D! (T:\coding\speed-grader\speed-grader\.next\server\app\api\text\route.js:132:1)
    at __webpack_require__ (T:\coding\speed-grader\speed-grader\.next\server\webpack-runtime.js:33:42)
    at __webpack_exec__ (T:\coding\speed-grader\speed-grader\.next\server\app\api\text\route.js:996:39)
    at T:\coding\speed-grader\speed-grader\.next\server\app\api\text\route.js:997:28
    at Object.<anonymous> (T:\coding\speed-grader\speed-grader\.next\server\app\api\text\route.js:1000:3)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at requirePage (T:\coding\speed-grader\speed-grader\node_modules\next\dist\server\require.js:112:75)
    at T:\coding\speed-grader\speed-grader\node_modules\next\dist\server\load-components.js:80:84
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async loadComponentsImpl (T:\coding\speed-grader\speed-grader\node_modules\next\dist\server\load-components.js:80:26)
    at async DevServer.findPageComponentsImpl (T:\coding\speed-grader\speed-grader\node_modules\next\dist\server\next-server.js:772:36) {
  digest: undefined
}
null
```

Here is my file tree:

![image](https://github.com/tuffstuff9/nextjs-pdf-parser/assets/67878058/fa61e62c-60f0-4045-96c9-f73bb2ed5c51)

Here is what I pass in insomnia and get back:
![image](https://github.com/tuffstuff9/nextjs-pdf-parser/assets/67878058/62c31192-f2b0-4ad2-bcdd-ccf62f1dff5d)

**Comment by kleenkanteen** [comment]
I am on W10. I cloned the fresh repo. I was getting an error from route.ts, line 22, `const tempFilePath = `/tmp/${fileName}.pdf`;`. I had to change the path to a valid one on my computer like `const tempFilePath = `/coding/test/${fileName}.pdf`;`. The beginning starts at your C: drive. /tmp/ exists only on mac.
